# Generated by Django 4.0 on 2021-12-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keytrack', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='projects',
            field=models.ManyToManyField(to='keytrack.Project'),
        ),
    ]
