# Generated by Django 4.0 on 2021-12-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keytrack', '0004_designation_person_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='host_ip',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='host_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='host_type',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('laptop', 'Laptop'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
