# Generated by Django 4.0 on 2021-12-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keytrack', '0007_person_host_os_alter_person_host_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='has_vpn_access',
            field=models.BooleanField(default=False),
        ),
    ]
