# Generated by Django 4.0 on 2021-12-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keytrack', '0008_person_has_vpn_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='projects_with_db_access',
            field=models.ManyToManyField(related_name='db_accessor', to='keytrack.Project'),
        ),
        migrations.AddField(
            model_name='person',
            name='projects_with_live_server_access',
            field=models.ManyToManyField(related_name='live_server_accessor', to='keytrack.Project'),
        ),
    ]
