# Generated by Django 4.0 on 2021-12-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keytrack', '0012_person_repos_with_read_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='iam_user',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
