# Generated by Django 4.0 on 2021-12-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keytrack', '0013_person_iam_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='host_ip',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='host_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='iam_user',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='projects',
            field=models.ManyToManyField(blank=True, to='keytrack.Project'),
        ),
        migrations.AlterField(
            model_name='person',
            name='projects_with_db_access',
            field=models.ManyToManyField(blank=True, related_name='db_accessor', to='keytrack.Project'),
        ),
        migrations.AlterField(
            model_name='person',
            name='projects_with_live_server_access',
            field=models.ManyToManyField(blank=True, related_name='live_server_accessor', to='keytrack.Project'),
        ),
        migrations.AlterField(
            model_name='person',
            name='repos_with_read_access',
            field=models.ManyToManyField(blank=True, related_name='repo_reader', to='keytrack.Repository'),
        ),
        migrations.AlterField(
            model_name='person',
            name='repos_with_write_access',
            field=models.ManyToManyField(blank=True, related_name='repo_writer', to='keytrack.Repository'),
        ),
    ]
