# Generated by Django 4.0 on 2021-12-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keytrack', '0014_person_notes_alter_person_host_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deployment_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('docker', 'Docker'), ('k8s', 'Kubernetes'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
