# Generated by Django 4.0 on 2022-01-03 06:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keytrack', '0016_project_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='jenkins_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4096), default=[], size=None),
        ),
    ]
