# Generated by Django 4.0.4 on 2022-04-22 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keytrack', '0019_alter_person_jenkins_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('ip', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(choices=[('desktop', 'Desktop'), ('laptop', 'Laptop'), ('other', 'Other')], default='other', max_length=32)),
                ('os', models.CharField(choices=[('mswin', 'Windows'), ('mac', 'Mac OS'), ('linux', 'Linux-based'), ('other', 'Other')], default='other', max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='host_ip',
        ),
        migrations.RemoveField(
            model_name='person',
            name='host_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='host_os',
        ),
        migrations.RemoveField(
            model_name='person',
            name='host_type',
        ),
        migrations.AddField(
            model_name='person',
            name='hosts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='keytrack.host'),
        ),
    ]
