# Generated by Django 4.0.4 on 2022-04-22 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keytrack', '0020_host_remove_person_host_ip_remove_person_host_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubkey', models.CharField(max_length=4096)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='keytrack.host')),
            ],
        ),
    ]
