# Generated by Django 4.0.4 on 2022-04-22 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keytrack', '0021_sshkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshkey',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='keytrack.person'),
        ),
    ]
