# Generated by Django 4.0.4 on 2022-04-23 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keytrack', '0022_alter_sshkey_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='managers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='keytrack.person'),
        ),
    ]
