# Generated by Django 4.0.4 on 2022-04-24 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keytrack', '0023_person_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfRegisterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epsid', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='keytrack.designation')),
                ('managers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='keytrack.selfregisterrequest')),
                ('projects', models.ManyToManyField(blank=True, to='keytrack.project')),
            ],
        ),
    ]
