# Generated by Django 4.0.4 on 2022-04-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keytrack', '0024_selfregisterrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfregisterrequest',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
