# Generated by Django 4.0.4 on 2022-04-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keytrack', '0025_selfregisterrequest_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfregisterrequest',
            name='managers',
        ),
        migrations.AddField(
            model_name='selfregisterrequest',
            name='managers',
            field=models.ManyToManyField(blank=True, to='keytrack.selfregisterrequest'),
        ),
    ]
