# Generated by Django 4.0.4 on 2022-04-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keytrack', '0026_remove_selfregisterrequest_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfregisterrequest',
            name='managers',
            field=models.ManyToManyField(blank=True, to='keytrack.person'),
        ),
    ]
