# Generated by Django 4.0.4 on 2022-04-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keytrack', '0027_alter_selfregisterrequest_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='managers',
        ),
        migrations.AddField(
            model_name='person',
            name='managers',
            field=models.ManyToManyField(blank=True, to='keytrack.person'),
        ),
    ]
