version: "3.3"
   
services:
  db:
    container_name: keytrack-db-con
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./env/db.env
  sess:
    container_name: keytrack-sess-con
    image: redis
    command: >
      --requirepass ${REDIS_PASSWORD}
  web:
    container_name: keytrack-web-con
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./env/sess.env
      - ./env/web.env
      # For REDIS_PASSWORD
      - .env
    depends_on:
      - db
      - sess
