version: "3.3"
   
services:
  db:
    container_name: keytrack-db-con
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      # POSTGRES_PASSWORD
      - ./env/db.secret.env
  sess:
    container_name: keytrack-sess-con
    image: redis
    command: >
      --requirepass ${REDIS_PASSWORD}
  web:
    container_name: keytrack-web-con
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - KEYTRACK_WEBSESSDB_HOST=keytrack-sess-con
      - KEYTRACK_WEBSESSDB_PORT=6379
    env_file:
      # TODO SECURITY use settings.py since password in django env are unsafe?
      # POSTGRES_PASSWORD
      - ./env/db.secret.env
      # POSTGRES_NAME and POSTGRES_USER
      - ./env/db.env
      # For REDIS_PASSWORD
      - .env
    depends_on:
      - db
      - sess
